---
services:
  toolbox:
    build: .
    environment:
      DISPLAY: '${DISPLAY}'
      XAUTHORITY: '${XAUTHORITY}'
      XDG_SESSION_DESKTOP: '${XDG_SESSION_DESKTOP}'
      SDG_SESSION_TYPE: '${XDG_SESSION_TYPE}'
      XDG_RUNTIME_DIR: '${XDG_RUNTIME_DIR}'
      XDG_CURRENT_DESKTOP: '${XDG_CURRENT_DESKTOP}'
      XDG_SESSION_PATH: '${XDG_SESSION_PATH}'
      DBUS_SESSION_BUS_ADDRESS: '${DBUS_SESSION_BUS_ADDRESS}'
    volumes:
      - '/tmp/.X11-unix:/tmp/.X11-unix'
      - '${XAUTHORITY}:${XAUTHORITY}:ro'
      - '${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}'
    cap_add:
      - SYS_ADMIN
    devices:
      - '/dev/fuse:/dev/fuse'

